# Generated by Django 4.0.2 on 2022-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='feature/image')),
                ('icon', models.FileField(upload_to='feature/icon')),
                ('testimonial_logo', models.FileField(upload_to='feature/testimonial_logo')),
            ],
        ),
    ]
