# Generated by Django 4.0.2 on 2022-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='auther_desigination',
            field=models.CharField(default='adj', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='description',
            field=models.TextField(default='hgyg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='icon_background',
            field=models.CharField(default='ghg', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='testimonial_author',
            field=models.CharField(default='gjhg', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='testimonial_description',
            field=models.TextField(default='khu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feature',
            name='title',
            field=models.CharField(default='jhg', max_length=225),
            preserve_default=False,
        ),
    ]
