# Generated by Django 4.0.2 on 2022-03-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='video/image')),
                ('icon', models.FileField(upload_to='video/icon')),
                ('discribe', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('desigination', models.CharField(max_length=225)),
                ('company', models.CharField(max_length=225)),
            ],
        ),
    ]
