# Generated by Django 4.0.2 on 2022-03-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='market/image')),
                ('title', models.CharField(max_length=225)),
                ('discribe', models.CharField(max_length=225)),
            ],
        ),
    ]
