# Generated by Django 4.0.2 on 2022-03-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_marketing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketing',
            name='image',
            field=models.FileField(upload_to='market/image'),
        ),
    ]
